import { useState } from "react";
import { PFButton, PFSelect, PFTextField, PFCheckbox, PFSwitch, PFSegmentedControl, PFToolbar, PFToolbarGroup, PFInspectorSection, PFControlRow, PFPanel, PFPopover } from "./PlotFlowControls.jsx";
import "./PlotFlowDesignSystem.css";
import "./PlotFlowAdoption.css";

const groups = ["Hoàn thiện", "Giãn xây", "Xây thô"];

export default function PlotFlowDesignSystem() {
  const [group, setGroup] = useState(groups[0]);
  const [segment, setSegment] = useState("overview");
  return <main className="pf-ds-page">
    <header className="pf-ds-page-head"><div><span>PLOTFLOW DESIGN SYSTEM</span><h1>One visual language.<br/>Across every PlotFlow surface.</h1></div><p>Home and Detail keep PlotFlow's identity. Platform-native typography and macOS interaction discipline make controls, hierarchy, layout and states predictable.</p></header>
    <section className="pf-ds-section"><div className="pf-ds-section-head"><div><span>FOUNDATIONS</span><h2>Typography · spacing · surfaces</h2></div></div><div className="pf-ds-foundation-grid"><article className="pf-ds-type-card"><strong>UI type scale</strong><div className="pf-ds-type-stack"><b className="is-title1">Title 1</b><b className="is-title2">Title 2</b><b className="is-title3">Title 3</b><b className="is-headline">Headline</b><span className="is-body">Body — clear, compact product information.</span><small>Caption / metadata</small></div><em>Native system UI font on macOS and Windows. Brand typography remains available for editorial surfaces.</em></article><article><strong>Spacing</strong><div className="pf-ds-space-demo"><i/><i/><i/><i/></div><small>4 · 8 · 12 · 16 · 24 · 32</small></article><article><strong>Radius</strong><div className="pf-ds-radius-demo"><i/><i/><i/></div><small>Control · Button · Card</small></article><article><strong>Surface</strong><div className="pf-ds-surface-demo"><i/><i/><i/></div><small>Canvas · Soft · Raised</small></article></div></section>
    <section className="pf-ds-section"><div className="pf-ds-section-head"><div><span>COMPONENTS</span><h2>Core controls</h2></div></div><div className="pf-ds-showcase-grid"><article className="pf-ds-showcase-card"><strong>Buttons</strong><p>Immediate actions. Accent is reserved for primary or selected state.</p><div className="pf-ds-samples"><PFButton variant="primary">Save</PFButton><PFButton>Cancel</PFButton><PFButton variant="quiet">More</PFButton><PFButton variant="danger">Delete</PFButton><PFButton disabled>Disabled</PFButton></div></article><article className="pf-ds-showcase-card"><strong>Pop-up / Select</strong><p>One mutually exclusive choice when conserving space matters.</p><PFSelect label="Handover type" value={group} onChange={(e)=>setGroup(e.target.value)}>{groups.map(item=><option key={item}>{item}</option>)}</PFSelect></article><article className="pf-ds-showcase-card"><strong>Segmented control</strong><p>Use only when a small set benefits from staying visible.</p><PFSegmentedControl label="View" value={segment} onChange={setSegment} options={[{value:"overview",label:"Overview"},{value:"detail",label:"Detail"}]}/></article><article className="pf-ds-showcase-card"><strong>Text fields</strong><p>Labels stay outside values. Focus state is consistent everywhere.</p><PFTextField label="Unit code" defaultValue="TL3219" hint="Stable domain identifier"/></article><article className="pf-ds-showcase-card"><strong>Boolean controls</strong><p>Checkbox for inclusion; switch for an immediate on/off setting.</p><div className="pf-ds-stack"><PFCheckbox label="Include connectors" defaultChecked/><PFSwitch label="Snap guides" defaultChecked/></div></article><article className="pf-ds-showcase-card"><strong>Icon actions</strong><p>Familiar icon-only actions require accessible labels and tooltips.</p><PFToolbarGroup label="Canvas tools"><PFButton variant="selected" icon="↖" iconOnly aria-label="Select" title="Select"/><PFButton icon="✋" iconOnly aria-label="Pan" title="Pan"/><PFButton icon="−" iconOnly aria-label="Zoom out" title="Zoom out"/><PFButton icon="+" iconOnly aria-label="Zoom in" title="Zoom in"/></PFToolbarGroup></article></div></section>
    <section className="pf-ds-section"><div className="pf-ds-section-head"><div><span>LAYOUT</span><h2>Toolbar · panel · popover</h2></div></div><div className="pf-ds-layout-stack"><PFToolbar leading={<PFToolbarGroup label="History"><PFButton icon="↶" iconOnly aria-label="Undo"/><PFButton icon="↷" iconOnly aria-label="Redo"/></PFToolbarGroup>} center={<PFSegmentedControl value={segment} onChange={setSegment} options={[{value:"overview",label:"Overview"},{value:"detail",label:"Detail"}]}/>} trailing={<><PFButton variant="quiet">Guides</PFButton><PFButton variant="primary">Export</PFButton></>}/><div className="pf-ds-layout-grid"><PFPanel title="Object audit" subtitle="Current handover type" footer={<PFButton variant="quiet">Reveal all</PFButton>}><div className="pf-ds-list"><button>Cards <b>12</b></button><button>Connectors <b>11</b></button><button>Highlights <b>3</b></button></div></PFPanel><PFPopover title="Export"><PFSelect label="Format" defaultValue="png"><option value="png">PNG</option><option value="pdf">PDF</option></PFSelect><PFTextField label="Width" defaultValue="2400"/><PFButton variant="primary">Export image</PFButton></PFPopover></div></div></section>
    <section className="pf-ds-section"><div className="pf-ds-section-head"><div><span>PATTERNS</span><h2>Object inspector</h2></div></div><div className="pf-ds-pattern-grid"><aside className="pf-ds-inspector-demo"><PFInspectorSection title="Card" meta="2 selected"><PFControlRow label="Scale"><input type="range" min="20" max="100" defaultValue="100"/></PFControlRow><PFControlRow label="Align"><PFToolbarGroup label="Align cards"><PFButton icon="⇤" iconOnly aria-label="Align left"/><PFButton icon="↔" iconOnly aria-label="Center"/><PFButton icon="⇥" iconOnly aria-label="Align right"/></PFToolbarGroup></PFControlRow><PFControlRow label="Gap"><input className="pf-ds-number" type="number" defaultValue="12"/></PFControlRow></PFInspectorSection><PFInspectorSection title="Card appearance"><PFControlRow label="Corner radius"><input className="pf-ds-number" type="number" defaultValue="12"/></PFControlRow></PFInspectorSection></aside><article className="pf-ds-pattern-note"><strong>Object rule</strong><p>Choose an object → show only actions owned by that object. Shared tools stay outside the inspector. The same action must never appear twice.</p></article></div></section>
  </main>;
}
