import { useEffect } from "react";
import { toPng } from "html-to-image";
import "./OverviewZoomRuntime.css";

const MIN_SCALE = 0.7;
const MAX_SCALE = 12;
const DEFAULT_FOCUS_SCALE = 4.5;
const STORAGE_KEY = "phongflow-overview-markup-v2";
const CARD_LAYOUT_KEY = "phongflow-overview-card-layout-v2";

function clamp(value, min, max) { return Math.min(max, Math.max(min, value)); }
function readJson(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key) || "null"); return value ?? fallback; } catch { return fallback; } }
function clone(value) { return JSON.parse(JSON.stringify(value)); }

export default function OverviewZoomRuntime() {
  useEffect(() => {
    let cleanupStage = null;

    function attach(stage) {
      if (!stage || stage.dataset.pfOverviewZoomReady === "1") return;
      stage.dataset.pfOverviewZoomReady = "1";
      let scale = 1, tx = 0, ty = 0, tool = "select", stroke = 3, spaceDown = false, dragging = false, dragMode = "";
      let startX = 0, startY = 0, startTx = 0, startTy = 0, startScale = 1, zoomAnchorX = 0, zoomAnchorY = 0, zoomWorldX = 0, zoomWorldY = 0;
      let drawStart = null, focusedCode = "", interactionLockedUntil = 0;
      let markup = readJson(STORAGE_KEY, []); if (!Array.isArray(markup)) markup = [];
      let cardLayout = readJson(CARD_LAYOUT_KEY, {}); if (!cardLayout || typeof cardLayout !== "object" || Array.isArray(cardLayout)) cardLayout = {};
      let selectedCards = new Set(), keyCard = null, dragCardsStart = [], history = [], future = [], focusRaf = 0;

      const toolbar = document.createElement("div");
      toolbar.className = "pf-overview-zoom-toolbar pf-overview-editor-toolbar";
      toolbar.innerHTML = `<div class="pf-editor-tools"><button type="button" data-tool="select" class="active" title="Select (V)">↖</button><button type="button" data-tool="hand" title="Hand (H / Space)">✋</button><button type="button" data-tool="zoom" title="Zoom (Z)">Z</button><span class="pf-overview-zoom-divider"></span><button type="button" data-tool="line" title="Line (L)">╱</button><button type="button" data-tool="rect" title="Rectangle (R)">▭</button><label class="pf-stroke-control" title="Stroke width"><span>Stroke</span><select><option>1</option><option>2</option><option selected>3</option><option>4</option><option>6</option><option>8</option><option>12</option></select></label><button type="button" data-action="undo">↶</button><button type="button" data-action="redo">↷</button></div><div class="pf-editor-layout-tools"><button type="button" data-layout="same">Same</button><button type="button" data-layout="left">L</button><button type="button" data-layout="hcenter">C</button><button type="button" data-layout="right">R</button><button type="button" data-layout="top">T</button><button type="button" data-layout="vcenter">M</button><button type="button" data-layout="bottom">B</button><button type="button" data-layout="space-v">Dist V</button></div><div class="pf-editor-view-tools"><button type="button" data-action="png">PNG</button><button type="button" data-action="pdf">PDF</button><span class="pf-overview-zoom-divider"></span><button type="button" data-action="out">−</button><output>100%</output><button type="button" data-action="in">+</button><button type="button" data-action="fit">Fit</button></div>`;
      stage.appendChild(toolbar);
      const markupLayer = document.createElementNS("http://www.w3.org/2000/svg", "svg"); markupLayer.setAttribute("class", "pf-overview-markup-layer"); markupLayer.setAttribute("viewBox", "0 0 1000 1000"); markupLayer.setAttribute("preserveAspectRatio", "none"); stage.appendChild(markupLayer);
      const output = toolbar.querySelector("output"), strokeSelect = toolbar.querySelector("select");
      const transformTargets = () => Array.from(stage.querySelectorAll(".pf-callout-layer,.pf-overview-coming,.pf-overview-markup-layer"));
      const getCards = () => Array.from(stage.querySelectorAll(".pf-live-sales-callout,.pf-sales-callout"));
      const codeForCard = (card) => card?.dataset?.unitCode || card?.querySelector(".pf-sell-card-code,header strong")?.textContent?.trim() || "";
      const getAnchor = (code) => Array.from(stage.querySelectorAll(".pf-live-map-anchor,.pf-map-anchor")).find((n) => (n.dataset?.unitCode || n.textContent?.trim()) === code) || null;
      const getLineForCode = (code) => Array.from(stage.querySelectorAll(".pf-live-callout-lines line,.pf-callout-lines line")).find((l) => l.dataset?.unitCode === code) || null;
      const worldMetrics = (card) => ({ left: card.offsetLeft, top: card.offsetTop, width: card.offsetWidth, height: card.offsetHeight });
      const persistCard = (card) => { const code = codeForCard(card); if (!code) return; const m = worldMetrics(card); cardLayout[code] = { left:+m.left.toFixed(2), top:+m.top.toFixed(2), width:+m.width.toFixed(2), height:+m.height.toFixed(2) }; };
      const saveCardLayout = () => localStorage.setItem(CARD_LAYOUT_KEY, JSON.stringify(cardLayout));
      function applyStoredCardLayout(){ getCards().forEach(card=>{const s=cardLayout[codeForCard(card)]; if(!s)return; card.style.left=`${s.left}px`;card.style.top=`${s.top}px`;card.style.right="auto";card.style.width=`${s.width}px`;card.style.height=`${s.height}px`;card.style.minHeight=`${s.height}px`;}); updateConnectors(); }
      const snapshot=()=>{getCards().forEach(persistCard);return{markup:clone(markup),cardLayout:clone(cardLayout)}};
      function pushHistory(){history.push(snapshot());if(history.length>60)history.shift();future=[]}
      function restore(state){if(!state)return;markup=clone(state.markup||[]);cardLayout=clone(state.cardLayout||{});localStorage.setItem(STORAGE_KEY,JSON.stringify(markup));saveCardLayout();renderMarkup();applyStoredCardLayout()}
      function undo(){if(!history.length)return;future.push(snapshot());restore(history.pop())} function redo(){if(!future.length)return;history.push(snapshot());restore(future.pop())}
      const saveMarkup=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(markup));
      function renderMarkup(draft=null){const items=draft?[...markup,draft]:markup;markupLayer.innerHTML=items.map(item=>item.type==="line"?`<line x1="${item.x1}" y1="${item.y1}" x2="${item.x2}" y2="${item.y2}" stroke="#ff3b30" stroke-width="${item.stroke}" vector-effect="non-scaling-stroke"/>`:`<rect x="${Math.min(item.x1,item.x2)}" y="${Math.min(item.y1,item.y2)}" width="${Math.abs(item.x2-item.x1)}" height="${Math.abs(item.y2-item.y1)}" fill="rgba(255,59,48,.10)" stroke="#ff3b30" stroke-width="${item.stroke}" vector-effect="non-scaling-stroke"/>`).join("");updateConnectors()}
      function updateConnectors(){const w=stage.clientWidth||1,h=stage.clientHeight||1;getCards().forEach(card=>{const code=codeForCard(card),line=getLineForCode(code),anchor=getAnchor(code);if(!line||!anchor)return;const m=worldMetrics(card);const ax=Number.parseFloat(anchor.style.left||"50"),ay=Number.parseFloat(anchor.style.top||"50");const anchorPx=ax/100*w,cardCenter=m.left+m.width/2;const startX=anchorPx>=cardCenter?m.left+m.width:m.left;line.setAttribute("x1",String(startX/w*100));line.setAttribute("y1",String((m.top+m.height/2)/h*100));line.setAttribute("x2",String(ax));line.setAttribute("y2",String(ay));});}
      function refreshSelectionUi(){getCards().forEach(card=>{card.classList.toggle("pf-card-selected",selectedCards.has(card));card.classList.toggle("pf-card-key",keyCard===card&&selectedCards.has(card));})}
      function selectCard(card,event){if(event.shiftKey){selectedCards.has(card)?selectedCards.delete(card):selectedCards.add(card);if(!selectedCards.has(keyCard))keyCard=card;}else{selectedCards=new Set([card]);keyCard=card;}refreshSelectionUi()}
      const selectedOrAll=()=>selectedCards.size?Array.from(selectedCards):getCards();
      function applyCardMetric(card,next){card.style.left=`${next.left}px`;card.style.top=`${next.top}px`;card.style.right="auto";card.style.width=`${next.width}px`;card.style.height=`${next.height}px`;card.style.minHeight=`${next.height}px`;persistCard(card)}
      function alignSelection(kind){const cards=selectedOrAll();if(!cards.length)return;pushHistory();const key=keyCard&&cards.includes(keyCard)?keyCard:cards[0],km=worldMetrics(key);cards.forEach(card=>{const m=worldMetrics(card),n={...m};if(kind==="same"){n.width=km.width;n.height=km.height}if(kind==="left")n.left=km.left;if(kind==="hcenter")n.left=km.left+km.width/2-m.width/2;if(kind==="right")n.left=km.left+km.width-m.width;if(kind==="top")n.top=km.top;if(kind==="vcenter")n.top=km.top+km.height/2-m.height/2;if(kind==="bottom")n.top=km.top+km.height-m.height;applyCardMetric(card,n)});saveCardLayout();updateConnectors()}
      function distributeVertical(){const cards=selectedOrAll();if(cards.length<3)return;const sorted=cards.map(card=>({card,m:worldMetrics(card)})).sort((a,b)=>a.m.top-b.m.top),first=sorted[0].m,last=sorted.at(-1).m,total=sorted.reduce((s,i)=>s+i.m.height,0),gap=(last.top+last.height-first.top-total)/(sorted.length-1);let cursor=first.top;sorted.forEach(({card,m})=>{applyCardMetric(card,{...m,top:cursor});cursor+=m.height+gap});saveCardLayout();updateConnectors()}
      function emitCamera(){window.dispatchEvent(new CustomEvent("pf-overview-camera",{detail:{scale,tx,ty,dragging}}))}
      function apply(){const transform=`translate3d(${tx}px,${ty}px,0) scale(${scale})`;transformTargets().forEach(node=>{node.style.transformOrigin="0 0";node.style.transform=transform;node.style.willChange=dragging?"transform":"auto"});output.textContent=`${Math.round(scale*100)}%`;stage.style.setProperty("--pf-overview-zoom",scale);updateConnectors();emitCamera()}
      function setTool(next){tool=next;toolbar.querySelectorAll("[data-tool]").forEach(b=>b.classList.toggle("active",b.dataset.tool===tool));stage.dataset.overviewTool=tool}
      function zoomAt(clientX,clientY,nextScale){const rect=stage.getBoundingClientRect(),px=clientX-rect.left,py=clientY-rect.top,worldX=(px-tx)/scale,worldY=(py-ty)/scale,resolved=clamp(nextScale,MIN_SCALE,MAX_SCALE);tx=px-worldX*resolved;ty=py-worldY*resolved;scale=resolved;apply()}
      function animateCamera(next,duration=360){cancelAnimationFrame(focusRaf);const from={scale,tx,ty},started=performance.now();dragging=true;const tick=now=>{const p=clamp((now-started)/duration,0,1),e=1-Math.pow(1-p,4);scale=from.scale+(next.scale-from.scale)*e;tx=from.tx+(next.tx-from.tx)*e;ty=from.ty+(next.ty-from.ty)*e;apply();if(p<1)focusRaf=requestAnimationFrame(tick);else{dragging=false;apply()}};focusRaf=requestAnimationFrame(tick)}
      function focusToPoint(detail={}){const x=Number(detail.x),y=Number(detail.y);if(!Number.isFinite(x)||!Number.isFinite(y))return;const rect=stage.getBoundingClientRect(),targetScale=clamp(Number(detail.scale)||DEFAULT_FOCUS_SCALE,MIN_SCALE,MAX_SCALE),px=x/100*rect.width,py=y/100*rect.height;focusedCode=String(detail.code||"");interactionLockedUntil=performance.now()+420;setTool("select");animateCamera({scale:targetScale,tx:rect.width*.5-px*targetScale,ty:rect.height*.5-py*targetScale})}
      function fit(){cancelAnimationFrame(focusRaf);scale=1;tx=0;ty=0;dragging=false;apply()}
      function pointInWorld(event){const rect=stage.getBoundingClientRect();return{x:clamp((((event.clientX-rect.left)-tx)/scale/rect.width)*1000,-5000,5000),y:clamp((((event.clientY-rect.top)-ty)/scale/rect.height)*1000,-5000,5000)}}
      async function exportPng(){const prev=toolbar.style.display;toolbar.style.display="none";stage.classList.add("is-exporting-overview");try{const dataUrl=await toPng(stage,{pixelRatio:2.5,cacheBust:true,backgroundColor:"#fff"});const link=document.createElement("a");link.download=`PlotFlow-Overview-${Date.now()}.png`;link.href=dataUrl;link.click()}finally{toolbar.style.display=prev;stage.classList.remove("is-exporting-overview")}}
      async function exportPdf(){const prev=toolbar.style.display;toolbar.style.display="none";stage.classList.add("is-exporting-overview");try{const dataUrl=await toPng(stage,{pixelRatio:2.2,cacheBust:true,backgroundColor:"#fff"});const popup=window.open("","_blank","noopener,noreferrer");if(popup){popup.document.write(`<!doctype html><html><body style="margin:0"><img style="width:100vw;height:100vh;object-fit:contain" src="${dataUrl}" onload="setTimeout(()=>window.print(),150)"></body></html>`);popup.document.close()}}finally{toolbar.style.display=prev;stage.classList.remove("is-exporting-overview")}}
      function onWheel(event){if(performance.now()<interactionLockedUntil||!stage.contains(event.target)||toolbar.contains(event.target))return;event.preventDefault();zoomAt(event.clientX,event.clientY,scale*Math.exp(-event.deltaY*(event.ctrlKey?.004:.0018)))}
      function onPointerDown(event){if(event.button!==0||toolbar.contains(event.target))return;const card=event.target.closest?.(".pf-sales-callout,.pf-live-sales-callout"),wantsPan=spaceDown||tool==="hand",wantsZoom=tool==="zoom",wantsDraw=tool==="line"||tool==="rect",wantsCards=tool==="select"&&card;if(!wantsPan&&!wantsZoom&&!wantsDraw&&!wantsCards)return;event.preventDefault();dragging=true;dragMode=wantsPan?"pan":wantsZoom?"zoom":wantsDraw?"draw":"cards";startX=event.clientX;startY=event.clientY;startTx=tx;startTy=ty;startScale=scale;stage.setPointerCapture?.(event.pointerId);if(dragMode==="zoom"){const r=stage.getBoundingClientRect();zoomAnchorX=event.clientX-r.left;zoomAnchorY=event.clientY-r.top;zoomWorldX=(zoomAnchorX-tx)/scale;zoomWorldY=(zoomAnchorY-ty)/scale}if(dragMode==="draw"){pushHistory();drawStart=pointInWorld(event)}if(dragMode==="cards"){selectCard(card,event);pushHistory();dragCardsStart=selectedOrAll().map(c=>({card:c,m:worldMetrics(c)}))}apply()}
      function onPointerMove(event){if(!dragging)return;if(dragMode==="pan"){tx=startTx+(event.clientX-startX);ty=startTy+(event.clientY-startY)}else if(dragMode==="zoom"){scale=clamp(startScale*Math.exp(((event.clientX-startX)-(event.clientY-startY)*.35)*.008),MIN_SCALE,MAX_SCALE);tx=zoomAnchorX-zoomWorldX*scale;ty=zoomAnchorY-zoomWorldY*scale}else if(dragMode==="cards"){const dx=(event.clientX-startX)/scale,dy=(event.clientY-startY)/scale;dragCardsStart.forEach(({card,m})=>applyCardMetric(card,{...m,left:m.left+dx,top:m.top+dy}))}else if(drawStart){renderMarkup({type:tool,x1:drawStart.x,y1:drawStart.y,x2:pointInWorld(event).x,y2:pointInWorld(event).y,stroke})}apply()}
      function onPointerUp(event){if(!dragging)return;if(dragMode==="draw"&&drawStart){const end=pointInWorld(event);if(Math.hypot(end.x-drawStart.x,end.y-drawStart.y)>2){markup.push({type:tool,x1:drawStart.x,y1:drawStart.y,x2:end.x,y2:end.y,stroke,lotCode:focusedCode});saveMarkup()}drawStart=null;renderMarkup()}if(dragMode==="cards"){selectedOrAll().forEach(persistCard);saveCardLayout();updateConnectors()}dragging=false;dragMode="";stage.releasePointerCapture?.(event.pointerId);apply()}
      function onKeyDown(event){if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement||event.target instanceof HTMLSelectElement)return;const key=event.key.toLowerCase(),command=event.metaKey||event.ctrlKey;if(command&&key==="z"){event.preventDefault();event.shiftKey?redo():undo();return}if(command&&key==="y"){event.preventDefault();redo();return}if(event.code==="Space"){spaceDown=true;event.preventDefault();return}if(key==="z")setTool("zoom");if(key==="h")setTool("hand");if(key==="v")setTool("select");if(key==="l")setTool("line");if(key==="r")setTool("rect")}
      const onKeyUp=event=>{if(event.code==="Space")spaceDown=false};
      function onToolbarClick(event){const button=event.target.closest("button");if(!button)return;if(button.dataset.tool)setTool(button.dataset.tool);if(button.dataset.layout==="space-v")distributeVertical();else if(button.dataset.layout)alignSelection(button.dataset.layout);if(button.dataset.action==="fit")fit();if(button.dataset.action==="undo")undo();if(button.dataset.action==="redo")redo();if(button.dataset.action==="png")exportPng();if(button.dataset.action==="pdf")exportPdf();if(button.dataset.action==="in"||button.dataset.action==="out"){const r=stage.getBoundingClientRect(),factor=button.dataset.action==="in"?1.5:1/1.5;zoomAt(r.left+r.width/2,r.top+r.height/2,scale*factor)}}
      const onLiveUnitsReady=()=>requestAnimationFrame(()=>{applyStoredCardLayout();updateConnectors();apply()});
      stage.addEventListener("wheel",onWheel,{passive:false});stage.addEventListener("pointerdown",onPointerDown,true);stage.addEventListener("pointermove",onPointerMove);stage.addEventListener("pointerup",onPointerUp);stage.addEventListener("pointercancel",onPointerUp);toolbar.addEventListener("click",onToolbarClick);strokeSelect.addEventListener("change",()=>stroke=Number(strokeSelect.value)||3);window.addEventListener("keydown",onKeyDown,{passive:false});window.addEventListener("keyup",onKeyUp);window.addEventListener("pf-overview-live-units-ready",onLiveUnitsReady);window.addEventListener("pf-overview-focus-request",e=>focusToPoint(e.detail||{}));renderMarkup();applyStoredCardLayout();apply();
      cleanupStage=()=>{cancelAnimationFrame(focusRaf);stage.removeEventListener("wheel",onWheel);stage.removeEventListener("pointerdown",onPointerDown,true);stage.removeEventListener("pointermove",onPointerMove);stage.removeEventListener("pointerup",onPointerUp);stage.removeEventListener("pointercancel",onPointerUp);window.removeEventListener("keydown",onKeyDown);window.removeEventListener("keyup",onKeyUp);toolbar.remove();markupLayer.remove();delete stage.dataset.pfOverviewZoomReady};
    }
    function sync(){const stage=document.querySelector(".pf-masterplan-stage.has-real-pdf.has-callouts");if(stage&&stage.dataset.pfOverviewZoomReady!=="1")attach(stage)}
    sync();const observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});return()=>{observer.disconnect();cleanupStage?.()};
  },[]);
  return null;
}
