import { useEffect } from "react";
import "./OverviewLayoutGuardRuntime.css";

const GUIDE_KEY="plotflow-overview-guides-v2";
const CARD_LAYOUT_KEY="phongflow-overview-card-layout-v2";
const PRECISION_KEY="plotflow-overview-precision-arrange-v2";
const BASE_CARD_WIDTH=192;
function clamp(v,min,max){return Math.max(min,Math.min(max,Number(v)||0))}
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}}
function codeFor(card){return card?.dataset?.unitCode||card?.querySelector(".pf-sell-card-code")?.textContent?.trim()||""}

export default function OverviewLayoutGuardRuntime(){
 useEffect(()=>{
  let disposed=false,stage=null,rail=null,sizeControl=null,observer=null,cardDrag=null,snapMarker=null,needsFit=true;
  const cards=()=>stage?Array.from(stage.querySelectorAll(".pf-live-sales-callout")):[];
  function pdfBounds(){if(!stage)return null;const x=Number(stage.dataset.pfPdfX),y=Number(stage.dataset.pfPdfY),width=Number(stage.dataset.pfPdfWidth),height=Number(stage.dataset.pfPdfHeight);return[x,y,width,height].every(Number.isFinite)&&width>2&&height>2?{x,y,width,height}:null}
  function persistCards(list=cards()){const layout=readJson(CARD_LAYOUT_KEY,{});list.forEach(card=>{const code=codeFor(card);if(code)layout[code]={left:card.offsetLeft,top:card.offsetTop,width:card.offsetWidth,height:card.offsetHeight}});localStorage.setItem(CARD_LAYOUT_KEY,JSON.stringify(layout))}
  function setCardSize(card,width,height){const w=clamp(width,64,420),h=clamp(height,56,420);card.style.setProperty("--pf-card-width",`${w}px`);card.style.setProperty("--pf-card-height",`${h}px`);card.style.setProperty("--pf-card-content-scale",String(clamp(w/BASE_CARD_WIDTH,.34,2.2)));card.style.width=`${w}px`;card.style.height=`${h}px`;card.style.minHeight=`${h}px`;card.style.right="auto"}
  function ensureCardsFit(){const list=cards();if(!list.length)return;requestAnimationFrame(()=>{let changed=false;list.forEach(card=>{const required=Math.ceil(card.scrollHeight);if(required>card.offsetHeight+1){card.style.setProperty("--pf-card-height",`${required}px`);card.style.height=`${required}px`;card.style.minHeight=`${required}px`;changed=true}});if(changed)persistCards(list)})}
  function applyAllSize(width,height){const list=cards();if(!list.length)return;const w=clamp(width,64,420),h=clamp(height,56,420);list.forEach(card=>setCardSize(card,w,h));const p=readJson(PRECISION_KEY,{});p.cardWidth=w;p.cardHeight=h;localStorage.setItem(PRECISION_KEY,JSON.stringify(p));persistCards(list);ensureCardsFit();window.dispatchEvent(new CustomEvent("pf-overview-all-card-size",{detail:{width:w,height:h,count:list.length}}))}
  function gridTarget(card){if(!card||!stage)return null;const guides=readJson(GUIDE_KEY,{});if(guides.snapGrid===false)return null;const bounds=pdfBounds();if(!bounds)return null;const size=clamp(guides.gridSize??16,8,64),localLeft=card.offsetLeft-bounds.x,localTop=card.offsetTop-bounds.y,snappedLeft=Math.round(localLeft/size)*size,snappedTop=Math.round(localTop/size)*size;return{bounds,size,left:bounds.x+snappedLeft,top:bounds.y+snappedTop,dx:snappedLeft-localLeft,dy:snappedTop-localTop}}
  function showSnapPreview(card){const target=gridTarget(card);if(!target||!stage){card?.classList.remove("pf-grid-snap-candidate");if(snapMarker)snapMarker.hidden=true;return}if(!snapMarker?.isConnected){snapMarker=document.createElement("div");snapMarker.className="pf-grid-snap-marker";stage.appendChild(snapMarker)}card.classList.add("pf-grid-snap-candidate");snapMarker.hidden=false;snapMarker.style.left=`${target.left}px`;snapMarker.style.top=`${target.top}px`;snapMarker.style.width=`${Math.min(target.size,card.offsetWidth)}px`;snapMarker.style.height=`${Math.min(target.size,card.offsetHeight)}px`}
  function clearSnapPreview(){cards().forEach(card=>card.classList.remove("pf-grid-snap-candidate"));if(snapMarker)snapMarker.hidden=true}
  function snapDraggedCards(){if(!cardDrag||!stage)return;const candidate=cardDrag.card,target=gridTarget(candidate);cardDrag=null;if(!candidate?.isConnected||!target){clearSnapPreview();return}const selected=cards().filter(card=>card.classList.contains("pf-card-selected")),list=selected.length?selected:[candidate];list.forEach(card=>{card.style.left=`${clamp(card.offsetLeft+target.dx,target.bounds.x,target.bounds.x+target.bounds.width-card.offsetWidth)}px`;card.style.top=`${clamp(card.offsetTop+target.dy,target.bounds.y,target.bounds.y+target.bounds.height-card.offsetHeight)}px`;card.style.right="auto"});persistCards(list);clearSnapPreview();stage.classList.add("pf-grid-snap-flash");setTimeout(()=>stage?.classList.remove("pf-grid-snap-flash"),220);window.dispatchEvent(new CustomEvent("pf-overview-auto-arranged",{detail:{mode:"grid-snap"}}))}
  function onPointerDown(event){if(event.button!==0)return;const card=event.target.closest?.(".pf-live-sales-callout");if(!card||!stage?.contains(card))return;cardDrag={card,pointerId:event.pointerId};showSnapPreview(card)}
  function onPointerMove(event){if(!cardDrag||event.pointerId!==cardDrag.pointerId)return;requestAnimationFrame(()=>showSnapPreview(cardDrag?.card))}
  function onPointerUp(event){if(!cardDrag||event.pointerId!==cardDrag.pointerId)return;snapDraggedCards()}
  function triggerFit(){if(!document.body.classList.contains("pf-product-overview"))return;document.querySelector('.pf-overview-zoom-toolbar [data-action="fit"]')?.click();needsFit=false}
  function requestFit(){needsFit=true;requestAnimationFrame(()=>requestAnimationFrame(triggerFit))}
  function onPdfBounds(){if(needsFit)requestAnimationFrame(triggerFit);ensureCardsFit()}
  function onGroupChanged(){needsFit=false;ensureCardsFit()}
  function installSizeControl(){rail=document.querySelector(".pf-overview-control-rail");if(!rail||sizeControl?.isConnected)return;const precision=readJson(PRECISION_KEY,{}),startW=clamp(precision.cardWidth??180,64,420),startH=clamp(precision.cardHeight??132,56,420);sizeControl=document.createElement("div");sizeControl.className="pf-overview-all-size-control";sizeControl.innerHTML=`<span>All cards</span><label>W <input data-all-width type="number" min="64" max="420" step="1" value="${startW}"><b>px</b></label><label>H <input data-all-height type="number" min="56" max="420" step="1" value="${startH}"><b>px</b></label><label class="pf-all-size-lock"><input data-all-lock type="checkbox" ${precision.constrain===false?"":"checked"}><b>Lock ratio</b></label><button type="button" data-all-apply>Apply</button>`;const width=sizeControl.querySelector("[data-all-width]"),height=sizeControl.querySelector("[data-all-height]"),lock=sizeControl.querySelector("[data-all-lock]");let ratio=startW/Math.max(1,startH);function saveLock(){const p=readJson(PRECISION_KEY,{});p.constrain=lock.checked;localStorage.setItem(PRECISION_KEY,JSON.stringify(p));if(lock.checked)ratio=Number(width.value)/Math.max(1,Number(height.value))}lock.addEventListener("change",saveLock);width.addEventListener("input",()=>{if(!lock.checked)return;const w=clamp(width.value,64,420),h=clamp(w/Math.max(.01,ratio),56,420);height.value=String(Math.round(h))});height.addEventListener("input",()=>{if(!lock.checked)return;const h=clamp(height.value,56,420),w=clamp(h*ratio,64,420);width.value=String(Math.round(w))});sizeControl.querySelector("[data-all-apply]").addEventListener("click",()=>applyAllSize(width.value,height.value));rail.appendChild(sizeControl)}
  function attach(nextStage){if(!nextStage||nextStage===stage)return;if(stage){stage.removeEventListener("pointerdown",onPointerDown,true);stage.removeEventListener("pointermove",onPointerMove,true);stage.removeEventListener("pointerup",onPointerUp,true);stage.removeEventListener("pointercancel",onPointerUp,true)}clearSnapPreview();stage=nextStage;stage.addEventListener("pointerdown",onPointerDown,true);stage.addEventListener("pointermove",onPointerMove,true);stage.addEventListener("pointerup",onPointerUp,true);stage.addEventListener("pointercancel",onPointerUp,true);requestFit();ensureCardsFit()}
  function sync(){if(disposed)return;installSizeControl();const next=document.querySelector(".pf-masterplan-stage.has-real-pdf.has-callouts");if(next&&next!==stage)attach(next)}
  window.addEventListener("pf-overview-pdf-bounds",onPdfBounds);window.addEventListener("pf-overview-group-changed",onGroupChanged);window.addEventListener("pf-overview-live-units-ready",sync);observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:["class"]});sync();return()=>{disposed=true;observer?.disconnect();window.removeEventListener("pf-overview-pdf-bounds",onPdfBounds);window.removeEventListener("pf-overview-group-changed",onGroupChanged);window.removeEventListener("pf-overview-live-units-ready",sync);if(stage){stage.removeEventListener("pointerdown",onPointerDown,true);stage.removeEventListener("pointermove",onPointerMove,true);stage.removeEventListener("pointerup",onPointerUp,true);stage.removeEventListener("pointercancel",onPointerUp,true)}clearSnapPreview();snapMarker?.remove();sizeControl?.remove()}
 },[]);return null;
}
