import { useEffect } from "react";
import "./OverviewArrangeModesRuntime.css";

const CARD_LAYOUT_KEY="phongflow-overview-card-layout-v2";
const PRECISION_KEY="plotflow-overview-precision-arrange-v2";
const BASE_CARD_WIDTH=192;
function clamp(v,min,max){return Math.max(min,Math.min(max,Number(v)||0))}
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key)||"null")??fallback}catch{return fallback}}
function codeFor(card){return card?.dataset?.unitCode||card?.querySelector(".pf-sell-card-code")?.textContent?.trim()||""}

export default function OverviewArrangeModesRuntime(){
  useEffect(()=>{
    let disposed=false,stage=null,observer=null;
    const cards=()=>stage?Array.from(stage.querySelectorAll(".pf-live-sales-callout")):[];
    function pdfBounds(){if(!stage)return null;const x=Number(stage.dataset.pfPdfX),y=Number(stage.dataset.pfPdfY),width=Number(stage.dataset.pfPdfWidth),height=Number(stage.dataset.pfPdfHeight);return[x,y,width,height].every(Number.isFinite)&&width>2&&height>2?{x,y,width,height}:null}
    function anchorFor(card){const code=codeFor(card),anchor=Array.from(stage?.querySelectorAll(".pf-live-map-anchor")||[]).find(n=>(n.dataset.unitCode||n.textContent?.trim())===code);return{x:clamp(Number.parseFloat(anchor?.style.left||"50"),0,100),y:clamp(Number.parseFloat(anchor?.style.top||"50"),0,100)}}
    function persist(){const layout={};cards().forEach(card=>{const code=codeFor(card);if(code)layout[code]={left:card.offsetLeft,top:card.offsetTop,width:card.offsetWidth,height:card.offsetHeight}});localStorage.setItem(CARD_LAYOUT_KEY,JSON.stringify(layout))}
    function setCardSize(card,width,height){const w=clamp(width,64,420),h=clamp(height,56,420);card.style.setProperty("--pf-card-width",`${w}px`);card.style.setProperty("--pf-card-height",`${h}px`);card.style.setProperty("--pf-card-content-scale",String(clamp(w/BASE_CARD_WIDTH,.34,2.2)));card.style.width=`${w}px`;card.style.height=`${h}px`;card.style.minHeight=`${h}px`;card.style.right="auto"}
    function fitCamera(){document.querySelector('.pf-overview-zoom-toolbar [data-action="fit"]')?.click()}
    function compactColumn(items,bounds,gap){if(!items.length)return gap;const insetY=18,minGap=4;let total=items.reduce((s,item)=>s+item.card.offsetHeight,0);const available=bounds.height-insetY*2;let resolvedGap=Math.min(gap,items.length>1?Math.max(minGap,(available-total)/(items.length-1)):0);let used=total+Math.max(0,items.length-1)*resolvedGap;if(used<=available)return resolvedGap;const targetCardArea=Math.max(56*items.length,available-Math.max(0,items.length-1)*minGap),ratio=clamp(targetCardArea/Math.max(total,1),.52,1);items.forEach(({card})=>setCardSize(card,card.offsetWidth*ratio,card.offsetHeight*ratio));total=items.reduce((s,item)=>s+item.card.offsetHeight,0);resolvedGap=items.length>1?Math.max(2,Math.min(gap,(available-total)/(items.length-1))):0;return Math.max(0,resolvedGap)}
    function placeColumn(items,side,bounds,gap,laneOffset=0){if(!items.length)return;const insetX=22,insetY=18,sorted=[...items].sort((a,b)=>a.anchor.y-b.anchor.y||codeFor(a.card).localeCompare(codeFor(b.card))),resolvedGap=compactColumn(sorted,bounds,gap),totalHeight=sorted.reduce((s,i)=>s+i.card.offsetHeight,0)+Math.max(0,sorted.length-1)*resolvedGap;let top=Math.max(bounds.y+insetY,bounds.y+(bounds.height-totalHeight)/2);sorted.forEach(({card})=>{const base=side==="left"?bounds.x+insetX:bounds.x+bounds.width-insetX-card.offsetWidth;const left=base+(side==="left"?laneOffset:-laneOffset);card.style.left=`${clamp(left,bounds.x+insetX,Math.max(bounds.x+insetX,bounds.x+bounds.width-insetX-card.offsetWidth))}px`;card.style.top=`${clamp(top,bounds.y+insetY,Math.max(bounds.y+insetY,bounds.y+bounds.height-insetY-card.offsetHeight))}px`;card.style.right="auto";top+=card.offsetHeight+resolvedGap})}
    function splitSmart(items){const left=[],right=[];[...items].sort((a,b)=>a.anchor.y-b.anchor.y).forEach(item=>{if(item.anchor.x<47)left.push(item);else if(item.anchor.x>53)right.push(item);else (left.length<=right.length?left:right).push(item)});while(Math.abs(left.length-right.length)>1){const from=left.length>right.length?left:right,to=from===left?right:left;to.push(from.splice(Math.floor(from.length/2),1)[0])}return{left,right}}
    function arrange(mode){const bounds=pdfBounds(),list=cards();if(!bounds||!list.length)return;fitCamera();const gap=clamp(readJson(PRECISION_KEY,{}).gap??14,0,120),items=list.map(card=>({card,anchor:anchorFor(card)}));let left=[],right=[];if(mode==="left")left=items;else if(mode==="right")right=items;else if(mode==="even"){[...items].sort((a,b)=>a.anchor.y-b.anchor.y).forEach((item,i)=>(i%2?right:left).push(item))}else({left,right}=splitSmart(items));placeColumn(left,"left",bounds,gap);placeColumn(right,"right",bounds,gap);persist();window.dispatchEvent(new CustomEvent("pf-overview-auto-arranged",{detail:{mode:`preset-${mode}`,left:left.length,right:right.length,gap}}));requestAnimationFrame(fitCamera)}
    function enhanceArrangeUi(){const popover=document.querySelector(".pf-layout-map-popover");if(!popover||popover.querySelector(".pf-arrange-mode-grid"))return;const footer=popover.querySelector("footer"),legacy=footer?.querySelector('[data-layout-ui="tidy"]');if(legacy)legacy.style.display="none";const modes=document.createElement("div");modes.className="pf-arrange-mode-grid";modes.innerHTML=`<button type="button" data-pf-arrange-mode="smart"><strong>Smart balance</strong><small>Anchor-aware · dense safe</small></button><button type="button" data-pf-arrange-mode="even"><strong>Even split</strong><small>Balanced left / right</small></button><button type="button" data-pf-arrange-mode="left"><strong>Left column</strong><small>Single clean column</small></button><button type="button" data-pf-arrange-mode="right"><strong>Right column</strong><small>Single clean column</small></button>`;modes.addEventListener("click",event=>{const button=event.target.closest("button[data-pf-arrange-mode]");if(!button)return;event.preventDefault();arrange(button.dataset.pfArrangeMode)});footer?.before(modes)}
    function sync(){if(disposed)return;stage=document.querySelector(".pf-masterplan-stage.has-real-pdf.has-callouts");enhanceArrangeUi()}
    window.addEventListener("pf-overview-live-units-ready",sync);window.addEventListener("pf-overview-pdf-bounds",sync);observer=new MutationObserver(sync);observer.observe(document.body,{childList:true,subtree:true});sync();return()=>{disposed=true;observer?.disconnect();window.removeEventListener("pf-overview-live-units-ready",sync);window.removeEventListener("pf-overview-pdf-bounds",sync);document.querySelector(".pf-arrange-mode-grid")?.remove()}
  },[]);return null;
}
